# Generated by Django 5.2.9 on 2025-12-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
