# Generated by Django 5.2.9 on 2025-12-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_missingperson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundperson',
            name='face_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='face_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
