# Generated by assistant to make FoundPerson.age_estimate nullable
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_foundperson_face_embedding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foundperson",
            name="age_estimate",
            field=models.PositiveIntegerField(null=True, blank=True),
        ),
    ]
