# Generated by Django 5.2.9 on 2025-12-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
