# Generated by Django 5.2.9 on 2025-12-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundperson',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
