# Generated by Django 5.2.9 on 2026-02-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_conversation_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foundperson',
            options={'ordering': ['-reported_at']},
        ),
        migrations.AlterModelOptions(
            name='missingperson',
            options={'ordering': ['-reported_at']},
        ),
        migrations.AddField(
            model_name='foundperson',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('closed', 'Closed')], db_index=True, default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('closed', 'Closed')], db_index=True, default='open', max_length=10),
        ),
    ]
