# Generated by Django 5.2.9 on 2026-02-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_foundperson_gender_alter_missingperson_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundperson',
            name='gender',
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
