# Generated by Django 5.2.9 on 2026-02-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_foundperson_gender_alter_missingperson_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundperson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='found_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='photo',
            field=models.ImageField(default='', upload_to='found_photos/'),
            preserve_default=False,
        ),
    ]
